version: "3.8"
services:
  character-api:
    build:
      context: ./
      dockerfile: infrastructure/Dockerfile
    container_name: character-api
    command: bash -c "uvicorn interface.main:app --host 0.0.0.0 --port 8000 --reload"
    volumes:
      - .:/backend
    ports:
      - "8000:8000"
    env_file:
      - ./.env
    depends_on:
      - db
    restart: always
  db:
    build:
      context: .
    command: [ "echo", "SQLite is running" ]